### ISSUE TITLE
Notification does not disappear within 10 MIN when MSW app is on background

### ISSUE THREAD

**Issue by udipo** [myspecialway/my-special-way-android#170] opened 2018-11-05 12:58 UTC
Notification does not disappear within 10 MIN when MSW app is on background and screen is powered-off (dark).

Notification is stuck at least 30 MIN after it presented on mobile screen.

**Comment by udipo** [comment] 2018-11-05 14:08
Notification does not disappear. New Notification is not presented any more … the old one is stuck on the mobile screen.

**Comment by nitzke** [comment] 2018-12-31 15:51
notification should disappear after 15 minutes, both reminders and schedules. agreed with Leora.

**Comment by nitzke** [comment] 2019-01-06 10:01
Hi.
It sounds like a duplicate of #192.
please retest as it shouldn't be relevant after latest changes.
Thanks

**Closed** 2019-01-27 15:57 UTC
Labels: Android, bug, review
